# This buildspec.yml can be built with aws/codebuild/ruby:2.3.1
version: 0.1

phases:
  install:
    commands:
      - |
        if [ "$BUILD_STAGE" == "Staging" ]; then
          echo "Installing gems with bundler"
          bundle install;
        else
          echo "Nothing to install. Moving to build stage";
        fi
  build:
    commands:

      - echo "Build Stage $BUILD_STAGE start"
      - |
        if [ "$BUILD_STAGE" == "Staging" ]; then
          echo "Build site and pushing to $STAGING_S3_BUCKET"
          bundle exec jekyll build
          aws s3 sync _site/ $STAGING_S3_BUCKET --exclude buildspec.yml
          BUILDMSG="Copy to staging complete.";
        elif [ "$BUILD_STAGE" == "Production" ]; then
          echo "Approval received"
          aws s3 sync $STAGING_S3_BUCKET $PROD_S3_BUCKET --exclude buildspec.yml
          aws s3 rm $STAGING_S3_BUCKET --recursive --exclude error.html
          BUILDMSG="Copy to production complete";
        else
          echo "Unknown error."
          BUILDMSG="Unknown error.";
        fi
      - echo "Build Stage $BUILD_STAGE complete"
    post_build:
      commands:
        - echo "*** Add SNS Notification here ***"
