# This buildspec.yml can be built with aws/codebuild/ruby:2.3.1
version: 0.1
   
phases:
  install:
    commands:
      # Add / remove whatever jekyll plugins you use here
      - echo "******** Installing gems ********"
      - gem install bundler
      - bundle install
  build:
    commands:
      - echo "******** Building site ********"
      - ls
      - bundle exec jekyll build
      - echo "******** Updating your jekyll website at s3 bucket ********"
      - echo "$TARGET_S3_BUCKET"
      - aws s3 sync _site/ $TARGET_S3_BUCKET
